[project]
authors = ["{{cookiecutter.workbench_maintainer_name}} {{cookiecutter.workbench_maintainer_email}}"]
channels = ["freecad/label/dev", "conda-forge"]
description = "{{cookiecutter.workbench_description}}"
name = "freecad.{{cookiecutter.workbench_module_name}}"
platforms = ["osx-arm64", "linux-aarch64", "linux-64", "win-64", "osx-64"]
version = "{{cookiecutter.workbench_version}}"

[pypi-dependencies]
freecad_{{cookiecutter.workbench_module_name}} = { path = ".", editable = true }

[tasks]
test = "python tests/tests.py"

[dependencies]
freecad = ">=1.0.0,<2"